=== NishChal370/MusicStore-XML/catalog_19031209.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT musicStore (fullPage_div?)>
<!ATTLIST musicStore xmlns:xsi CDATA #REQUIRED>
<!ATTLIST musicStore xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

<!-- Page content -->
<!ELEMENT fullPage_div (nav_div,  body_div)>

<!-- Navigation bar 'or'  nav:div-->
<!ELEMENT nav_div ( nav_left, nav_right)>
<!ELEMENT nav_left (logo)>
<!ELEMENT logo (#PCDATA)>
<!-- <!ELEMENT nav_right (#PCDATA)> -->
<!ELEMENT nav_right ( nav_title, nav_bottom)>
<!ELEMENT nav_title (#PCDATA)>
<!ELEMENT nav_bottom (nav_address, nav_website, nav_phone)>
<!ELEMENT nav_address (#PCDATA)>
<!ELEMENT nav_website (#PCDATA)>
<!ELEMENT nav_phone (#PCDATA)>

<!-- body 'or' body:div -->
<!ELEMENT body_div (menu_div, genres_div)>
<!-- menu div -->
<!ELEMENT menu_div (menu_title, menu_body)>
<!ATTLIST menu_div mid CDATA #REQUIRED>

<!ELEMENT menu_title (#PCDATA)>
<!ELEMENT menu_body (menu_list)+>

<!ELEMENT menu_list (menu)+>
<!ATTLIST menu_list id CDATA #REQUIRED>
<!ELEMENT menu (#PCDATA)>
<!ATTLIST menu id CDATA #REQUIRED>

<!-- Genres div-->
<!ELEMENT genres_div (genres_list)+>
<!ATTLIST genres_div id CDATA #REQUIRED>

<!ELEMENT genres_list (genres_title, genres_body)>
<!ATTLIST genres_list type CDATA #REQUIRED>
<!ATTLIST genres_list genreId CDATA #REQUIRED> 

<!ELEMENT genres_title (#PCDATA)>
<!ELEMENT genres_body (genre_origins?, (genre_form|genre_parentGenre)?, genre_album+)>
<!ATTLIST genres_body about CDATA #REQUIRED>

<!ELEMENT genre_origins (#PCDATA)>
<!ELEMENT genre_form (#PCDATA)>
<!ELEMENT genre_parentGenre (#PCDATA)>
<!-- Albums -->
<!ELEMENT genre_album (album_title, album_details, songs)+>
<!ATTLIST genre_album artist CDATA #REQUIRED>

<!ELEMENT album_title (#PCDATA)>
<!-- Album details -->
<!ELEMENT album_details (album_logo, album_detail)>
<!-- album cover image -->
<!ELEMENT album_logo (#PCDATA)>
<!ATTLIST album_logo id CDATA #REQUIRED>
<!-- album detail -->
<!ELEMENT album_detail (artist+, album+, release?, recorded?, album_length?, (studio|venue)?, album_member?, writers?)>
<!ATTLIST album_detail id CDATA #REQUIRED>
<!ELEMENT artist (a_title,data)>
<!ELEMENT a_title (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT recorded (#PCDATA)>
<!ELEMENT album_length (#PCDATA)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT venue (#PCDATA)>

<!ELEMENT album_member (listTitle, member+)>
<!ATTLIST album_member memberType CDATA #FIXED "Band_member">

<!ELEMENT listTitle (#PCDATA)>
<!ELEMENT member (#PCDATA)>

<!ELEMENT writers (#PCDATA)>

<!-- songs -->
<!ELEMENT songs (title?, song+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT song (song_name,length)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT song_name (#PCDATA)>

=== NishChal370/MusicStore-XML/catalog_19031209.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicStore SYSTEM "catalog_19031209.dtd">
<?xml-stylesheet type="text/css" href="catalog_19031209.css"?>
<!-- Nischal Bishwokarma  19031209 -->
<musicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031209.xsd">

    <fullPage_div>
        <!-- Navigation -->
        <nav_div>
            <nav_left>
                <logo></logo>
            </nav_left>
            <nav_right>
                <nav_title>Music Store</nav_title>
                <nav_bottom>
                    <nav_address>Kamal Pokhari; Kathmandu</nav_address>
                    <nav_website>wwww.musicStore.com.np</nav_website>
                    <nav_phone>+977-9805654362</nav_phone>    
                </nav_bottom>        
            </nav_right>
        </nav_div>

        <!-- Body -->
        <body_div>
            <menu_div mid="div1">
                <!-- body main title -->
                <menu_title>Genre</menu_title>
                <menu_body>
                    <!-- Genre List -->
                    <menu_list id="genreList_01">
                        <menu id="li1">Rock</menu>
                        <menu id="li2">Blues</menu>
                        <menu id="li3">Jazz</menu>
                    </menu_list>
                    <menu_list id="genreList_02">
                        <menu id="li4">Hard Rock</menu>
                        <menu id="li5">Alternative Rock</menu>
                        <menu id="li6">Pop Rock</menu>
                    </menu_list>
                    <menu_list id="genreList_03">
                        <menu id="li7">Country Music</menu>
                    </menu_list>
                </menu_body>
            </menu_div>


            <!-- Genres Info -->
            <genres_div id="div2">

                <!-- Genre Number 1 -->
                <genres_list type="Rock" genreId=" G01">
                    <genres_title>Rock</genres_title>
                    <!-- Genre Detail -->
                    <genres_body about="Rock_Detail">
                        <genre_origins>Culture origins: 1950s and 1960s</genre_origins>
                        <genre_form>Derivative forms: Synth-pop, Orchestral pop, Post-progressive, Progressive pop</genre_form>
                        <!-- Album in this genre -->
                        <genre_album artist="Pink_Floyd">
                            <album_title>Pink Floyd - The Dark Side Of The Moon</album_title>
                            <album_details>
                                <album_logo id="floydCover"></album_logo>
                                <!-- Album Detail -->
                                <album_detail id="floydAlbumDetl">
                                    <artist><a_title>Artist:</a_title><data>Pink Floyd</data></artist>
                                    <album>Album: The Dark Side Of The Moon</album>
                                    <release>Release date: March 1, 1973</release>
                                    <recorded>Recorded: June 1972 – January 1973</recorded>
                                    <album_length>Length: 43:09</album_length>
                                    <studio>Studio: Abbey Road, London</studio>
                                    <!-- band memeber list -->
                                    <album_member memberType="Band_member">
                                        <listTitle>Memeber</listTitle>
                                        <member>Bassist/Vocalist: Roger Waters</member>
                                        <member>Guitarist/Vocalist: David Gilmour</member>
                                        <member>Keyboard/Vocalist: Rick Wright</member>
                                        <member>Drummer: Nick Mason</member>
                                    </album_member>
                                </album_detail>
                            </album_details>
                            <!-- Albums Songs -->
                            <songs>
                                <title>Songs</title>
                                <song>
                                    <song_name>Speak to Me / Breathe</song_name>
                                    <length>3:58</length>
                                </song>
                                <song>
                                    <song_name>On the Run</song_name>
                                    <length>3:36</length>
                                </song>
                                <song>
                                    <song_name>Time</song_name>
                                    <length>6:53</length>
                                </song>
                                <song>
                                    <song_name>The Great Gig in the Sky</song_name>
                                    <length>4:36</length>
                                </song>
                                <song>
                                    <song_name>Money</song_name>
                                    <length>6:23</length>
                                </song>
                                <song>
                                    <song_name>Us and Them (original stereo mix)</song_name>
                                    <length>7:51</length>
                                </song>
                                <song>
                                    <song_name>Any Colour You Like</song_name>
                                    <length>3:26</length>
                                </song>
                                <song>
                                    <song_name>Brain Damage</song_name>
                                    <length>3:49</length>
                                </song>
                                <song>
                                    <song_name>Eclipse</song_name>
                                    <length>2:03</length>
                                </song>
                            </songs>
                        </genre_album>
                    </genres_body>
                </genres_list>

                <!-- Genre Number 2-->
                <genres_list type="Blues" genreId=" G02">
                    <genres_title>Blues</genres_title>
                    <!-- Genre Detail -->
                    <genres_body about="Blues_Detail">
                        <genre_origins>Culture origins: 1860s, Deep South‎, U.S‎</genre_origins>
                        <genre_form>Derivative forms: Bluegrass, Country music, Jazz, Jug band, Ragtime, Rhythm and blues, Rock and roll</genre_form>
                        <!-- Album in this genre -->
                        <genre_album artist="BB-King">
                            <album_title>B.B. King - Live at the Regal</album_title>
                            <!-- Album Detail -->
                            <album_details>
                                <album_logo id="kingCover"></album_logo>
                                <album_detail id="kingsAlbumDetl">
                                    <artist><a_title>Artist:</a_title><data>B.B. King</data></artist>
                                    <album>Album: Live at the Regal</album>
                                    <release>Release date: 1965 (LP) 1997 (CD)</release>
                                    <recorded>Recorded: November 1964</recorded>
                                    <album_length>Length: 34:46</album_length>
                                    <venue>Venue: Regal Theater, Chicago, Illinois</venue>
                                    <album_member memberType="Band_member">
                                        <listTitle>Memeber</listTitle>
                                        <member>Bassist: Leo Lauchie</member>
                                        <member>Trumpet: Kenneth Sands</member>
                                        <member>Piano: Duke Jethro</member>
                                        <member>Drummer: Sonny Freeman</member>
                                        <member>Tenor Saxophone: Bobby Forte and Johnny Board</member>
                                    </album_member>
                                </album_detail>
                            </album_details>
                            <!-- Albums Songs -->
                            <songs>
                                <title>Songs</title>
                                <song>
                                    <song_name>Every Day I Have the Blues</song_name>
                                    <length>2:38</length>
                                </song>
                                <song>
                                    <song_name>Sweet Little Angel</song_name>
                                    <length>4:12</length>
                                </song>
                                <song>
                                    <song_name>It's My Own Fault</song_name>
                                    <length>3:29</length>
                                </song>
                                <song>
                                    <song_name>How Blue Can You Get</song_name>
                                    <length>3:44</length>
                                </song>
                                <song>
                                    <song_name>Please Love Me</song_name>
                                    <length>3:01</length>
                                </song>
                                <song>
                                    <song_name>You Upset Me Baby</song_name>
                                    <length>2:22</length>
                                </song>
                            </songs>
                        </genre_album>
                    </genres_body>
                </genres_list>

                <!-- Genre Number 3-->
                <genres_list type="Jazz" genreId=" G03">
